const teams = [
  {
    name: 'BOURNEMOUTH',
    city: 'Bournemouth, Dorset',
    founded: '10-07-1899',
    coach: 'E. Howe',
    stadium: 'Vitality Stadium',
    address: `Dean Court, Kings Park BH7 7AF Bournemouth, Dorset`,
    stadiumCapacity: 12000,
  },
  {
    name: 'MANCHESTER CITY',
    city: 'Manchester',
    founded: '10-07-1880',
    coach: 'Guardiola',
    stadium: 'Etihad Stadium',
    address: `Rowsley Street M11 3FF Manchester`,
    stadiumCapacity: 55097,
  },
  {
    name: 'NEWCASTLE UNITED',
    city: 'Newcastle upon Tyne',
    founded: '10-07-1892',
    coach: 'S. Bruce',
    stadium: 'St. James Park',
    address: `St. James' Park NE1 4ST Newcastle upon Tyne`,
    stadiumCapacity: 52389,
  },
  {
    name: 'SHEFFIELD UNITED',
    city: 'Sheffield',
    founded: '10-07-1889',
    coach: 'C. Wilder',
    stadium: 'Bramall Lane',
    address: `Bramall Lane S2 4SU Sheffield`,
    stadiumCapacity: 32702,
  },
  {
    name: 'TOTTENHAM HOTSPUR',
    city: 'London',
    founded: '10-07-1882',
    coach: 'M. Pochettino',
    stadium: 'Tottenham Hotspur Stadium',
    address: `Bill Nicholson Way, 748 High Road N17 OAP London`,
    stadiumCapacity: 62062,
  },
  {
    name: 'WEST HAM UNITED ',
    city: 'London',
    founded: '10-07-1895',
    coach: 'M. Pellegrini',
    stadium: 'London Stadium',
    address: `Green Street E13 9AZ London`,
    stadiumCapacity: 60000,
  },
  {
    name: 'ASTON VILLA',
    city: 'Birmingham',
    founded: '10-07-1874',
    coach: 'D. Smith',
    stadium: 'Villa Park',
    address: `Trinity Road B6 6HE Birmingham`,
    stadiumCapacity: 42788,
  },
  {
    name: 'BURNLEY',
    city: 'Burnley',
    founded: '10-07-1882',
    coach: 'S. Dyche',
    stadium: 'Turf Moo',
    address: `Harry Potts Way BB10 4BX Burnley, Lancashire`,
    stadiumCapacity: 22546,
  },
  {
    name: 'CRYSTAL PALACE',
    city: 'London',
    founded: '10-07-1905',
    coach: 'R. Hodgson',
    stadium: 'Selhurst Park',
    address: `Selhurst Park SE25 6PU London`,
    stadiumCapacity: 26309,
  },
  {
    name: 'LEICESTER CITY',
    city: 'Leicester, Leicestershire',
    founded: '10-07-1884',
    coach: 'B. Rodgers',
    stadium: 'King Power Stadium',
    address: `Filbert Way LE2 7FL Leicester`,
    stadiumCapacity: 32262,
  },
  {
    name: 'ARSENAL',
    city: 'London',
    founded: '10-07-1886',
    coach: 'B. Rodgers',
    stadium: 'Emirates Stadium',
    address: `Highbury House, 75 Drayton Park N5 1BU London`,
    stadiumCapacity: 60355,
  },
  {
    name: 'MANCHESTER UNITED',
    city: 'Manchester',
    founded: '10-07-1886',
    coach: 'O. Solskjær',
    stadium: 'Old Trafford',
    address: `Sir Matt Busby Way M16 0RA Manchester`,
    stadiumCapacity: 76212,
  },
  {
    name: 'NORWICH CITY',
    city: 'Norwich, Norfolk',
    founded: '10-07-1886',
    coach: 'D. Farke',
    stadium: 'Carrow Road',
    address: `Carrow Road NR1 1JE Norwich, Norfolk`,
    stadiumCapacity: 27244,
  },
  {
    name: 'SOUTHAMPTON',
    city: 'Southampton, Hampshire',
    founded: '10-07-1885',
    coach: 'R. Hasenhüttl',
    stadium: 'St. Marys Stadium',
    address: `Britannia Road S014 5FP Southampton, Hampshire `,
    stadiumCapacity: 32689,
  },
  {
    name: 'WATFORD',
    city: 'Watford',
    founded: '10-07-1881',
    coach: 'Javi Gracia',
    stadium: 'Vicarage Road',
    address: `Vicarage Road WD18 0ER Watford`,
    stadiumCapacity: 21577,
  },
  {
    name: 'WOLVERHAMPTON WANDERERS',
    city: 'Wolverhampton, West Midlands',
    founded: '10-07-1877',
    coach: 'Nuno Espírito Santo',
    stadium: 'Molineux Stadium',
    address: `Waterloo Road WV1 4QR Wolverhampton
        `,
    stadiumCapacity: 31700,
  },
  {
    name: 'BRIGHTON & HOVE ALBION',
    city: 'Falmer, East Sussex',
    founded: '10-07-1877',
    coach: 'G. Potter',
    stadium: 'The American Express Community Stadium',
    address: `Village Way BN1 9BL Brighton, East Sussex`,
    stadiumCapacity: 30750,
  },
  {
    name: 'CHELSEA',
    city: 'London',
    founded: '10-07-1877',
    coach: 'F. Lampard',
    stadium: 'Stamford Bridge',
    address: `Fulham Road SW6 1HS London`,
    stadiumCapacity: 41841,
  },
  {
    name: 'EVERTON',
    city: 'Liverpool',
    founded: '10-07-1877',
    coach: 'Marco Silva',
    stadium: 'Goodison Park',
    address: `Goodison RoadL4 4EL Liverpool
        `,
    stadiumCapacity: 40569,
  },
  {
    name: 'LIVERPOOL',
    city: 'Liverpool',
    founded: '10-07-1892',
    coach: 'Marco Silva',
    stadium: 'Anfield',
    address: `Anfield RoadL4 0TH Liverpool`,
    stadiumCapacity: 55212,
  },
];
module.exports = teams;
